### PR TITLE
Fixes #226 TomlTable.write() throws NoSuchElementException

### LINKED ISSUE #226: TomlTable.write() throws NoSuchElementException if children is empty
```kotlin
@Test
    fun emptyArrayInTableTest(){
        @Serializable
        data class EmbeddedData(val data: String = "embedded data")

        @Serializable
        data class EmptyListData(val content: List<EmbeddedData> = listOf() )
        
        assertEncodedEquals(
            value = EmptyListData(),
            expectedToml = ""
        )
    }
```

Throws:

```
List is empty.
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
	at com.akuleshov7.ktoml.tree.nodes.TomlTable.write(TomlTable.kt:83)
```

### PR DESCRIPTION
**Pull request by thomasgalvin**
Fixes #226 TomlTable.write() throws NoSuchElementExceptionthrows NoSuchElementException if children is empty

### CODE REVIEW

**Review by akuleshov7 — APPROVED** [review]
Thank you for your contribution and especially for writing a test!
Looks good

**Comment by thomasgalvin** [comment]
Glad to help! Thanks for making an awesome utility!

**Comment by akuleshov7** [comment]
> Glad to help! Thanks for making an awesome utility!

if you don't mind, may I would add you to our acknowledgement list?

**Comment by thomasgalvin** [comment]
> if you don't mind, may I add you to our acknowledgement list?

I'd love that, thanks!

**Pull request merged**
