### PR TITLE
Unify array of tables and primitive table

### LINKED ISSUE #142: Refactoring: unify the logic for TomlTablePrimitive and TomlArrayOfTables
Duplication happened during the implementation of `TomlArrayOfTables`

```
// FixMe: this class is mostly identical to the TomlTable - we should unify them together
```

### PR DESCRIPTION
**Pull request by NightEule5**
Fixes #142

### CODE REVIEW

**Comment by akuleshov7** [comment]
If possible and you don't mind - let's take it to the next release? This one is very heavy

**Comment by NightEule5** [comment]
Sure

**Comment by akuleshov7** [comment]
I have released 0.5.0 finally - will start reviewing of a PR after post release actions. Thank you for your huge changes in 0.5.0 release, btw 🙏 You are great! ❤️

**Review by akuleshov7 — APPROVED** [review]
Looked at PR, everything looks to be not harmful :) I do not think it should break something. LGTM, thank you! Good idea finally to unify tables and just have a type  for them

**Pull request merged**
